# Generated by Django 5.0 on 2023-12-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="user",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
