# Generated by Django 5.0 on 2023-12-17 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0003_alter_rating_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="orm.restaurant",
            ),
        ),
    ]
