# Generated by Django 4.2.7 on 2023-12-20 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0002_alter_userfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                upload_to="user_files",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "png", "jpg"])
                ],
            ),
        ),
    ]
