# Generated by Django 5.0 on 2023-12-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0002_rating_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="restaurant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="ratings",
                to="orm.restaurant",
            ),
        ),
    ]
