# Generated by Django 5.0 on 2023-12-20 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                upload_to="images",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "png", "jpg"])
                ],
            ),
        ),
    ]
