# Generated by Django 4.2.7 on 2023-12-21 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0003_alter_userfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfile",
            old_name="file",
            new_name="filename",
        ),
    ]
