# Generated by Django 4.2.7 on 2024-01-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0002_alter_staff_options_alter_staffrestaurant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrestaurant",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="orm.restaurant",
            ),
        ),
    ]
